### ISSUE TITLE
Tag 'final' missing

### ISSUE THREAD

**Issue by loulloudesn** [UCY-CS-EPL425/sp16_tm06#2]
@UCY-CS-EPL425/sp16_tm06 - The **_final_** tag is missing from Assignment1

**Comment by pparthenhs** [comment]
Καλησπέρα ,

                Όπως μας είχατε αναφέρει έλειπε από την άσκηση μας το Tag.To
οποίο και προσθέσαμε μετά την παρατήρηση σας το Σάββατο. Εάν υπάρχει κάποιο
πρόβλημα παρακαλώ ενημερώστε μας.


Ευχαριστούμε εκ των προτέρων και απολογούμαστε για την ταλαιπωρία,

Ομάδα 6
